# Generated by Django 5.1 on 2024-09-05 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_genrechoices'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GenreChoices',
        ),
        migrations.AlterField(
            model_name='movies',
            name='genre',
            field=models.CharField(choices=[('Action', 'Action'), ('Fiction', 'Fiction'), ('Thriller', 'Thriller')], max_length=200),
        ),
    ]
